### ISSUE TITLE
Paths

### ISSUE THREAD

**Issue by sUMmermixon** [Montana-Media-Arts/441-WebTech#4]
<img width="906" alt="screen shot 2018-01-26 at 9 10 19 pm" src="https://user-images.githubusercontent.com/31555135/35468546-6363e02a-02dd-11e8-86f6-4346f914a3a2.png">

Having trouble with the hero-image. Is my path correct?

**Comment by CEFSTUDIO** [comment]
I don't believe you need the "." in front of your path. I believe it should be- 
background-image: url("/images/mom_boys.jpg");

This assumes the image is in the images folder- which it appears to be. 

https://css-tricks.com/quick-reminder-about-file-paths/

Helpful reading- I was in this class awhile ago but I guess I was still subscribed to the forum. Might as well help.

**Comment by JonSwallow** [comment]
Hey Summer try ("images/mom_boys.jpg")   
I haven't started yet but I was just going over one from last semester I had used a separate folder for css but since it is in the same folder you should not need the  period before it.

**Comment by sUMmermixon** [comment]
@CEFSTUDIO Thank you! 
@JonSwallow Yay I'm so happy you are in this class with me too!! 

... I will give this a shot.

**Comment by JohnYingling** [comment]
Hi @JonSwallow! :D  Be prepared for more panic-stricken issues board posts from me this semester!  Heh.

**Comment by JonSwallow** [comment]
Hey @ John Yingling, you may be helping me this semester!!

**Comment by michaelmusick** [comment]
We will all be helping each other. And it will be great!

**Comment by JakeTheFlare** [comment]
Like @CEFSTUDIO said, the "." at the beginning isn't necessary.  In fact, you may not need that "/" at the beginning either (try experimenting with that).

**Comment by michaelmusick** [comment]
OK, got some things for you.

With regard to paths: when a path starts with a single `.`, it is explicitly telling the compiler to start in "this directory". This is _optional_, although I tend to include them, as it is a visual cue to me and other developers that the path starts _from this directory_. When you do not prepend your path with a `.`, you should instead start with the directory you are moving to. (i.e. `MyNewDirectory/rest-of-path`) and not start with a slash, as this tells some compilers to start "at the top of the path". So, as far as I am aware, and my testing seems to support, your CSS path should either be `href="HW-1/style.css"` or `href="./HW-1/style.css"`. I will continue to use the latter in my examples, you are free to use either. 

With regard to your hero-image linking problem. Unfortunately, you spelled "background" wrong in line 11.
You have; `backround-image: url("/images/mom_boys.jpg");`
It should be `background-image: url("./images/mom_boys.jpg");`

Another problem is with the size you assign to the .hero-image class. We cannot use "relative heights" for background images, as the HTML engine will collapse the element if it has not "text contents". So we have to use a true height of somesort. I would suggest ["viewer height" (`vh`)](https://css-tricks.com/fun-viewport-units/). So change line 12 to `height:100vh;`. 

Finally, as a last note, your line 1 is superfluous and may cause errors. We do not declare "doctype" in CSS, as there is no doctype. That is a HTML specific requirement. Since there are multiple versions of HTML (i.e. XHTML HTML1.0, etc) we must declare the doctype for browsers to be sure of which to use. 

So, your updated `style.css` should be something like;

```css
body {
  height: 100%;
  background-color: black;
  color:white;
}

.hero-image {
  background-image: url("./images/mom_boys.jpg");
  height:100vh;
  background-position: center;
  background-repeat: no-repeat;
  background size: cover;
  position: relative;
}

.hero-text {
  text-align: center;
  position: absolute;
  top: 50%;
  left: 50%;
  transfrom: translate (-50%, -50%);
  color: white;
}
```

Let me know if that all works or not?
